### ISSUE TITLE
SQL Issue

### ISSUE THREAD

**Issue by OfficerZentro** [only-a-ptr/multiplayer.rigsofrods.org#1]
The following error occurs:
`Server error, cannot read database.`

This error happens when SQL results return false.

Example of the error located here: https://ror.avrintech.net/ror-serverlist-test/serverlist.php
This error could be linked to an improperly exported SQL Dump file.
(adding to this, I had to do a bit of editing to even get to this page, however that editing is not related to the following error.)

**Comment by only-a-ptr** [comment]
Don't install it in public yet, it's pre-alpha!

Anyway, the problem were wrong column names in SQL. Fixed in previous commit.
